package byog.Test;

import byog.Action.Action;
import byog.Action.ActionOutcome;
import byog.AI.AiTickContext;
import byog.AI.DecisionValidator;
import byog.AI.IntentLease;
import byog.Bridge.AgentProtocol;
import byog.Entity.Enemy;
import byog.Entity.EntityManager;
import byog.Entity.Player;
import byog.Perception.ObservationEnvelope;
import byog.TileEngine.TETile;
import byog.TileEngine.Tileset;
import byog.lab5.Position;

import org.junit.Test;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Random;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

/**
 * Arbitration and lease tests for the production intent arbiter.
 * Pure Java, no network, no sleep. Tests the Lease/Validator/Arbiter/ReflexController chain.
 */
public class AgentArbiterTest {

    private static final String RUN_ID = "agent-test-run";
    private static final int FLOOR_ID = 3;
    private static final long SESSION_EPOCH = 1;
    private static final long REQUEST_GENERATION = 1;

    // ────────── Arbiter-A01 ──────────

    /**
     * Arbiter-A01: remote CHASE intent goes through Validator/Lease/Planner.
     * The action is generated by Java's ClassicalPlanner, not directly by Python.
     */
    @Test
    public void remote_intent_goes_through_java_planner() {
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(5, 1), 10);
        fixture.prime();

        // Adopt a remote CHASE intent targeting the visible player
        DecisionValidator.ValidationResult result = fixture.adoptChase(
                "decision-1", 0, new Position(5, 1));
        assertEquals(DecisionValidator.ValidationResult.ACCEPTED, result);

        fixture.tick(0);

        ActionOutcome outcome = fixture.enemy.getLastActionOutcome();
        assertNotNull(outcome);
        assertEquals(AgentProtocol.DecisionSource.REMOTE_AGENT,
                outcome.getDecisionSource());
        assertEquals("MoveAction", outcome.getActionType());
        // Enemy should have moved toward the player
        assertEquals(new Position(2, 1), fixture.enemy.getPosition());
    }

    // ────────── Arbiter-A02 ──────────

    /**
     * Arbiter-A02: rejected intent has no side effects on lease/queue/cooldown.
     */
    @Test
    public void invalid_intent_has_no_side_effects() {
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(15, 1), 10);
        fixture.prime();

        assertEquals(DecisionValidator.ValidationResult.ACCEPTED,
                fixture.adoptPatrol(
                        "decision-1", 0, new Position(5, 1)));
        fixture.tick(0);

        IntentLease leaseBefore =
                fixture.enemy.getArbiter().getCurrentLease();
        IntentLease.LeaseState stateBefore = leaseBefore.getState();
        int queueSizeBefore = fixture.enemy.getActionQueue().size();
        Position positionBefore = fixture.enemy.getPosition();
        int hpBefore = fixture.enemy.getHp();
        boolean overrideBefore =
                fixture.enemy.getArbiter().isInReflexOverride();
        String overrideReasonBefore =
                fixture.enemy.getArbiter().getOverrideReason();
        ActionOutcome outcomeBefore =
                fixture.enemy.getLastActionOutcome();

        // Try to adopt an intent with out-of-bounds target
        DecisionValidator.ValidationResult result = fixture.adoptChase(
                "decision-2",
                fixture.enemy.getLatestObservation().getObservationSeq(),
                new Position(999, 999));
        assertEquals(DecisionValidator.ValidationResult.TARGET_OUT_OF_BOUNDS,
                result);

        assertSame(leaseBefore,
                fixture.enemy.getArbiter().getCurrentLease());
        assertEquals(stateBefore, leaseBefore.getState());
        assertEquals(queueSizeBefore,
                fixture.enemy.getActionQueue().size());
        assertEquals(positionBefore, fixture.enemy.getPosition());
        assertEquals(hpBefore, fixture.enemy.getHp());
        assertEquals(overrideBefore,
                fixture.enemy.getArbiter().isInReflexOverride());
        assertEquals(overrideReasonBefore,
                fixture.enemy.getArbiter().getOverrideReason());
        assertSame(outcomeBefore, fixture.enemy.getLastActionOutcome());
    }

    // ────────── Arbiter-A03 ──────────

    /**
     * Arbiter-A03: when the remote agent is slow, the enemy continues the old plan.
     * Uses a PATROL lease with player not visible, so P3 is selected.
     */
    @Test
    public void old_plan_continues_while_agent_slow() {
        // Player far away, not visible
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(15, 1), 10);
        fixture.prime();

        // Adopt a remote PATROL intent targeting a visible walkable tile
        DecisionValidator.ValidationResult result = fixture.adoptPatrol(
                "decision-1", 0, new Position(5, 1));
        assertEquals(DecisionValidator.ValidationResult.ACCEPTED, result);

        // Execute first tick: P3 uses lease, plans and moves
        fixture.tick(0);
        Position posAfterTick0 = fixture.enemy.getPosition();
        assertEquals(new Position(2, 1), posAfterTick0);
        ActionOutcome outcome0 = fixture.enemy.getLastActionOutcome();
        assertEquals(AgentProtocol.DecisionSource.REMOTE_AGENT,
                outcome0.getDecisionSource());
        assertEquals("decision-1", outcome0.getDecisionId());

        // No new intent arrives (agent is slow). Execute second tick: P3 continues
        fixture.tick(1);
        Position posAfterTick1 = fixture.enemy.getPosition();
        assertEquals(new Position(3, 1), posAfterTick1);
        ActionOutcome outcome1 = fixture.enemy.getLastActionOutcome();
        assertEquals(AgentProtocol.DecisionSource.REMOTE_AGENT,
                outcome1.getDecisionSource());
        // Same decision, incremented action index
        assertEquals("decision-1", outcome1.getDecisionId());
        assertEquals(outcome0.getActionIndex() + 1, outcome1.getActionIndex());
    }

    // ────────── Arbiter-A04 ──────────

    /**
     * Arbiter-A04: with no remote lease, the local brain takes over.
     * Player not visible so P4 (local fallback) is selected.
     */
    @Test
    public void no_plan_uses_local_brain() {
        // Player far away, not visible
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(15, 1), 10);
        fixture.prime();

        // No remote lease adopted
        assertNull(fixture.enemy.getArbiter().getCurrentLease());

        fixture.tick(0);

        // Enemy should have acted using local fallback
        ActionOutcome outcome = fixture.enemy.getLastActionOutcome();
        assertNotNull(outcome);
        assertEquals(AgentProtocol.DecisionSource.LOCAL_FALLBACK,
                outcome.getDecisionSource());
        // Local fallback lease should now exist
        IntentLease lease = fixture.enemy.getArbiter().getCurrentLease();
        assertNotNull(lease);
        assertEquals(AgentProtocol.DecisionSource.LOCAL_FALLBACK,
                lease.getDecisionSource());
    }

    // ────────── Arbiter-A05 ──────────

    /**
     * Arbiter-A05: when the player enters FOV while the agent is waiting,
     * the next action tick triggers P2 reflex engage.
     */
    @Test
    public void visible_player_triggers_next_action_tick() {
        // Player far away, not visible initially
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(15, 1), 10);
        fixture.prime();

        // Adopt PATROL lease (player not visible -> not stale)
        DecisionValidator.ValidationResult result = fixture.adoptPatrol(
                "decision-1", 0, new Position(5, 1));
        assertEquals(DecisionValidator.ValidationResult.ACCEPTED, result);

        // Execute tick 0: P3 (player not visible, no P2)
        fixture.tick(0);
        ActionOutcome outcome0 = fixture.enemy.getLastActionOutcome();
        assertNull(outcome0.getOverrideReason());

        // Move player into FOV
        fixture.player.setPosition(new Position(5, 1));
        // 刷新 observation：生产帧序中，玩家移动后的状态由本帧末尾的 collect 捕获，
        // 下一帧 execute 才会读到。这里手动刷新等效于跨过了那一道帧边界。
        fixture.refreshObservation();

        // Tick 1: execute uses refreshed observation -> P2 triggers
        fixture.tick(1);
        ActionOutcome outcome1 = fixture.enemy.getLastActionOutcome();
        assertNotNull(outcome1);
        assertEquals("P2_VISIBLE_PLAYER", outcome1.getOverrideReason());
        // P2 reflex action should move toward player
        assertEquals("MoveAction", outcome1.getActionType());
    }

    // ────────── Arbiter-A06 ──────────

    /**
     * Arbiter-A06: GUARD policy with engageVisiblePlayer=false limits P2 but not P1.
     * Player visible but not adjacent -> P2 suppressed, P3 used.
     * Player adjacent -> P1 still triggers.
     */
    @Test
    public void fresh_guard_policy_limits_p2_not_p1() {
        // Player at distance 2, visible but not adjacent
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(3, 1), 10);
        fixture.prime();

        // Adopt GUARD lease with engageVisiblePlayer=false
        DecisionValidator.ValidationResult result = fixture.adoptGuard(
                "decision-1", 0, new Position(5, 1),
                false);
        assertEquals(DecisionValidator.ValidationResult.ACCEPTED, result);

        // Execute tick 0: P2 should NOT trigger (policy disallows)
        fixture.tick(0);
        ActionOutcome outcome0 = fixture.enemy.getLastActionOutcome();
        assertNotNull(outcome0);
        // P3 used (no reflex override)
        assertNull(outcome0.getOverrideReason());
        assertEquals(AgentProtocol.DecisionSource.REMOTE_AGENT,
                outcome0.getDecisionSource());

        // Move player adjacent to enemy's new position
        Position enemyPos = fixture.enemy.getPosition();
        fixture.player.setPosition(new Position(enemyPos.x + 1, enemyPos.y));

        // Tick 1: P1 should trigger (adjacent, regardless of policy)
        fixture.tick(1);
        ActionOutcome outcome1 = fixture.enemy.getLastActionOutcome();
        assertNotNull(outcome1);
        assertEquals("P1_ADJACENT_THREAT", outcome1.getOverrideReason());
        assertEquals("AttackAction", outcome1.getActionType());
    }

    // ────────── Arbiter-A07 ──────────

    /**
     * Arbiter-A07: a stale PATROL intent (based on old observation without player)
     * cannot override the current reflex engage when player is visible.
     */
    @Test
    public void stale_patrol_cannot_override_reflex_engage() {
        // 请求产生时玩家不可见，PATROL 当时合法。
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(15, 1), 10);
        fixture.prime();
        ObservationEnvelope oldObservation =
                fixture.enemy.getLatestObservation();

        // 等待期间玩家进入 FOV。
        fixture.player.setPosition(new Position(5, 1));
        fixture.refreshObservation();

        // 当前 tick 先触发 P2。
        fixture.tick(1);
        ActionOutcome outcome0 = fixture.enemy.getLastActionOutcome();
        assertEquals("P2_VISIBLE_PLAYER", outcome0.getOverrideReason());

        // 迟到 PATROL 仍基于旧 observation，不能覆盖当前反射。
        DecisionValidator.ValidationResult result =
                fixture.adoptPatrolFromObservation(
                        "decision-1", oldObservation,
                        new Position(5, 1), 2);
        assertEquals(DecisionValidator.ValidationResult.STALE_PRECONDITION,
                result);

        // No lease adopted, P2 reflex continues
        assertNull(fixture.enemy.getArbiter().getCurrentLease());

        fixture.tick(2);
        ActionOutcome outcome1 = fixture.enemy.getLastActionOutcome();
        assertEquals("P2_VISIBLE_PLAYER", outcome1.getOverrideReason());
    }

    // ────────── Arbiter-A08 ──────────

    /**
     * Arbiter-A08: when the player leaves FOV, the reflex override ends.
     * The fast brain does not read the hidden player position.
     * The old lease only resumes if its precondition still holds.
     */
    @Test
    public void hidden_player_position_not_used() {
        // Player visible initially
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(3, 1), 10);
        fixture.prime();

        // Adopt a CHASE lease (player visible -> not stale)
        DecisionValidator.ValidationResult result = fixture.adoptChase(
                "decision-1", 0, new Position(3, 1));
        assertEquals(DecisionValidator.ValidationResult.ACCEPTED, result);
        IntentLease remoteLease =
                fixture.enemy.getArbiter().getCurrentLease();

        // Tick 0: P2 triggers (CHASE lease, player visible)
        fixture.tick(0);
        ActionOutcome outcome0 = fixture.enemy.getLastActionOutcome();
        assertEquals("P2_VISIBLE_PLAYER", outcome0.getOverrideReason());

        // Move player far away (out of FOV)
        fixture.player.setPosition(new Position(15, 1));
        // 刷新 observation：让 latestReflexObservation 反映玩家已离开 FOV
        fixture.refreshObservation();

        // Tick 1: execute uses refreshed observation -> P2 no longer triggers, override ends
        fixture.tick(1);
        ActionOutcome outcome1 = fixture.enemy.getLastActionOutcome();
        // Override should have ended
        assertNull(outcome1.getOverrideReason());

        // 原远程 lease 必须明确失效，并由新的本地 lease 接管。
        assertEquals(IntentLease.LeaseState.STALE,
                remoteLease.getState());
        IntentLease currentLease =
                fixture.enemy.getArbiter().getCurrentLease();
        assertNotNull(currentLease);
        assertNotSame(remoteLease, currentLease);
        assertEquals(AgentProtocol.DecisionSource.LOCAL_FALLBACK,
                currentLease.getDecisionSource());
        assertEquals(AgentProtocol.DecisionSource.LOCAL_FALLBACK,
                outcome1.getDecisionSource());
    }

    @Test
    public void hidden_target_is_not_authorized_by_full_world() {
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(15, 1), 5);
        fixture.prime();

        DecisionValidator.ValidationResult result = fixture.adoptGuard(
                "decision-hidden", 0, new Position(10, 1), false);

        assertEquals(DecisionValidator.ValidationResult.TARGET_NOT_KNOWN,
                result);
        assertNull(fixture.enemy.getArbiter().getCurrentLease());
    }

    @Test
    public void expired_remote_patrol_is_replaced_by_local_lease() {
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(15, 1), 10);
        fixture.prime();

        assertEquals(DecisionValidator.ValidationResult.ACCEPTED,
                fixture.adoptPatrolWithTtl(
                        "decision-short", new Position(5, 1), 1));
        fixture.tick(0);
        assertEquals(AgentProtocol.DecisionSource.REMOTE_AGENT,
                fixture.enemy.getLastActionOutcome().getDecisionSource());

        fixture.tick(1);

        IntentLease current =
                fixture.enemy.getArbiter().getCurrentLease();
        assertNotNull(current);
        assertEquals(AgentProtocol.DecisionSource.LOCAL_FALLBACK,
                current.getDecisionSource());
        assertEquals(AgentProtocol.DecisionSource.LOCAL_FALLBACK,
                fixture.enemy.getLastActionOutcome().getDecisionSource());
        assertFalse("expired remote decisionId must not label fallback",
                "decision-short".equals(
                fixture.enemy.getLastActionOutcome().getDecisionId()));
    }

    @Test
    public void expired_guard_policy_cannot_suppress_p2_reflex() {
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(4, 1), 10);
        fixture.prime();

        assertEquals(DecisionValidator.ValidationResult.ACCEPTED,
                fixture.adoptGuardWithTtl(
                        "decision-guard", new Position(5, 1),
                        false, 1));
        fixture.tick(0);
        assertNull(fixture.enemy.getLastActionOutcome().getOverrideReason());

        fixture.tick(1);

        assertEquals("P2_VISIBLE_PLAYER",
                fixture.enemy.getLastActionOutcome().getOverrideReason());
    }

    @Test
    public void lease_terminal_states_and_target_are_immutable() {
        Position target = new Position(5, 1);
        byog.AI.StrategicIntent intent = new byog.AI.StrategicIntent(
                byog.AI.StrategicIntent.Goal.PATROL,
                byog.AI.StrategicIntent.Strategy.PATROL,
                target);
        IntentLease stale = new IntentLease(
                intent, "decision-stale", 0, 0, 2,
                byog.AI.InterruptPolicy.safeDefault(),
                AgentProtocol.DecisionSource.REMOTE_AGENT);

        target.x = 99;
        assertEquals(new Position(5, 1),
                stale.getIntent().getTargetPosition());
        Position returned = stale.getIntent().getTargetPosition();
        returned.x = 77;
        assertEquals(new Position(5, 1),
                stale.getIntent().getTargetPosition());

        stale.markStale();
        stale.markExpired();
        assertEquals(IntentLease.LeaseState.STALE, stale.getState());
        assertFalse(stale.resumeAt(0));

        IntentLease expired = new IntentLease(
                intent, "decision-expired", 0, 0, 1,
                byog.AI.InterruptPolicy.safeDefault(),
                AgentProtocol.DecisionSource.REMOTE_AGENT);
        expired.refreshExpiry(1);
        expired.markStale();
        assertEquals(IntentLease.LeaseState.EXPIRED,
                expired.getState());
        assertFalse(expired.resumeAt(1));
    }

    @Test
    public void p2_override_reason_upgrades_to_p1() {
        Fixture fixture = fixture(1, new Position(1, 1),
                new Position(5, 1), 10);
        fixture.prime();

        fixture.tick(0);
        assertEquals("P2_VISIBLE_PLAYER",
                fixture.enemy.getLastActionOutcome().getOverrideReason());

        Position enemyPosition = fixture.enemy.getPosition();
        fixture.player.setPosition(
                new Position(enemyPosition.x + 1, enemyPosition.y));
        fixture.refreshObservation();
        fixture.tick(1);

        assertEquals("P1_ADJACENT_THREAT",
                fixture.enemy.getLastActionOutcome().getOverrideReason());
        assertEquals("AttackAction",
                fixture.enemy.getLastActionOutcome().getActionType());
    }

    // ────────── Fixture ──────────

    private static Fixture fixture(int moveInterval, Position enemyPosition,
                                   Position playerPosition, int sightRange) {
        TETile[][] world = corridorWorld(20, 3);
        EntityManager entityMgr = new EntityManager();
        Player player = new Player(playerPosition, 100, 10);
        Enemy enemy = new Enemy(enemyPosition, Tileset.ENEMY,
                20, sightRange, moveInterval, 1, 0,
                new Random(42), "guard-a");
        entityMgr.addEntity(player);
        entityMgr.addEntity(enemy);
        return new Fixture(world, entityMgr, player, enemy);
    }

    private static TETile[][] corridorWorld(int width, int height) {
        TETile[][] world = new TETile[width][height];
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                world[x][y] = y == 1 ? Tileset.FLOOR : Tileset.WALL;
            }
        }
        return world;
    }

    private static final class Fixture {
        private final TETile[][] world;
        private final EntityManager entityMgr;
        private final Player player;
        private final Enemy enemy;

        private Fixture(TETile[][] world, EntityManager entityMgr,
                        Player player, Enemy enemy) {
            this.world = world;
            this.entityMgr = entityMgr;
            this.player = player;
            this.enemy = enemy;
        }

        private AiTickContext context(long tick) {
            return new AiTickContext(RUN_ID, FLOOR_ID, tick);
        }

        private void prime() {
            entityMgr.flushPendingChanges();
            enemy.collectAgentUpdates(context(0), world, entityMgr, player);
        }

        private void tick(long tick) {
            AiTickContext ctx = context(tick);
            enemy.pollAgentMessages(ctx);
            enemy.executeOneAction(ctx, world, entityMgr);
            entityMgr.flushPendingChanges();
            entityMgr.removeDeadEntities();
            enemy.collectAgentUpdates(ctx, world, entityMgr, player);
        }

        /**
         * 手动重跑一次 collectAgentUpdates，把当前玩家位置固化为 latestReflexObservation。
         * 生产帧序是 execute→collect，下一 tick 的 execute 才会读到新观察；
         * 测试在两次 tick 之间挪动玩家后调用此方法，等效于"上一帧 collect 已捕获新状态"。
         * 注意：Entity.setPosition 只改实体字段，不重建 EntityManager 索引，
         * 所以必须先 flushPendingChanges 让索引同步，否则 perception 查不到玩家新位置。
         */
        private void refreshObservation() {
            entityMgr.flushPendingChanges();
            enemy.collectAgentUpdates(context(0), world, entityMgr, player);
        }

        /** Adopt a remote CHASE intent targeting the given position. */
        private DecisionValidator.ValidationResult adoptChase(
                String decisionId, long observationSeq, Position target) {
            return adoptIntent(decisionId, observationSeq,
                    AgentProtocol.Skill.CHASE, target, true);
        }

        /** Adopt a remote PATROL intent targeting the given position. */
        private DecisionValidator.ValidationResult adoptPatrol(
                String decisionId, long observationSeq, Position target) {
            return adoptIntent(decisionId, observationSeq,
                    AgentProtocol.Skill.PATROL, target, true);
        }

        private DecisionValidator.ValidationResult adoptPatrolWithTtl(
                String decisionId, Position target, int validForTicks) {
            ObservationEnvelope source = enemy.getLatestObservation();
            return adoptIntentFromObservation(
                    decisionId, source,
                    AgentProtocol.Skill.PATROL, target,
                    true, validForTicks, 0);
        }

        private DecisionValidator.ValidationResult adoptPatrolFromObservation(
                String decisionId,
                ObservationEnvelope sourceObservation,
                Position target,
                long currentLogicalTick) {
            return adoptIntentFromObservation(
                    decisionId, sourceObservation,
                    AgentProtocol.Skill.PATROL, target,
                    true, 20, currentLogicalTick);
        }

        /** Adopt a remote GUARD intent with configurable engageVisiblePlayer. */
        private DecisionValidator.ValidationResult adoptGuard(
                String decisionId, long observationSeq, Position target,
                boolean engageVisiblePlayer) {
            return adoptIntent(decisionId, observationSeq,
                    AgentProtocol.Skill.GUARD, target, engageVisiblePlayer);
        }

        private DecisionValidator.ValidationResult adoptGuardWithTtl(
                String decisionId, Position target,
                boolean engageVisiblePlayer, int validForTicks) {
            ObservationEnvelope source = enemy.getLatestObservation();
            return adoptIntentFromObservation(
                    decisionId, source,
                    AgentProtocol.Skill.GUARD, target,
                    engageVisiblePlayer, validForTicks, 0);
        }

        private DecisionValidator.ValidationResult adoptIntent(
                String decisionId, long observationSeq,
                AgentProtocol.Skill skill, Position target,
                boolean engageVisiblePlayer) {
            ObservationEnvelope source = enemy.getLatestObservation();
            assertEquals("test request must use the captured observation",
                    observationSeq, source.getObservationSeq());
            return adoptIntentFromObservation(
                    decisionId, source, skill, target,
                    engageVisiblePlayer, 20, 0);
        }

        private DecisionValidator.ValidationResult adoptIntentFromObservation(
                String decisionId,
                ObservationEnvelope sourceObservation,
                AgentProtocol.Skill skill,
                Position target,
                boolean engageVisiblePlayer,
                int validForTicks,
                long currentLogicalTick) {

            Map<String, Object> params = new LinkedHashMap<>();
            params.put("targetPosition",
                    new AgentProtocol.PositionData(target.x, target.y));

            AgentProtocol.InterruptPolicyData policy =
                    new AgentProtocol.InterruptPolicyData(
                            engageVisiblePlayer, true, true);

            AgentProtocol.IntentData intent = new AgentProtocol.IntentData(
                    AgentProtocol.INTENT_VERSION, skill, params,
                    0.8, validForTicks, policy);

            AgentProtocol.SubmitIntentData proposal =
                    new AgentProtocol.SubmitIntentData(
                            decisionId,
                            sourceObservation.getObservationSeq(),
                            REQUEST_GENERATION,
                            intent);

            AgentProtocol.Envelope envelope = new AgentProtocol.Envelope(
                    AgentProtocol.ENVELOPE_VERSION,
                    "msg-1", 0,
                    "world-test", RUN_ID, FLOOR_ID, "guard-a",
                    SESSION_EPOCH, 0,
                    AgentProtocol.MessageType.SUBMIT_INTENT,
                    proposal);

            DecisionValidator.RequestExpectation expectation =
                    new DecisionValidator.RequestExpectation(
                            new AgentProtocol.Identity(
                                    "world-test", RUN_ID, FLOOR_ID, "guard-a",
                                    SESSION_EPOCH, REQUEST_GENERATION),
                            decisionId,
                            sourceObservation.getObservationSeq(),
                            REQUEST_GENERATION,
                            sourceObservation);

            return enemy.tryAdoptRemoteIntent(
                    proposal, envelope, expectation,
                    world, currentLogicalTick);
        }
    }
}
