package byog.Core;

import byog.Helper.Logger;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Properties;

/**
 * 游戏平衡配置管理。从 config/game.properties 加载，文件不存在时自动生成默认配置。
 */
public class GameConfig {
    private static final String CONFIG_PATH = "config/game.properties";

    public final Difficulty difficulty;
    public final int playerHp;
    public final int playerAttack;
    public final int playerDamageVariance;
    public final int playerMaxCharge;
    public final int playerChargeRate;
    public final int enemyHp;
    public final int enemyAttack;
    public final int enemyDamageVariance;
    public final int enemyMoveInterval;
    public final int enemySightRange;
    public final int enemyBaseCount;

    public GameConfig(Difficulty difficulty) {
        this.difficulty = difficulty;
        Properties props = load(difficulty);
        String prefix = difficulty.getKey() + ".";

        playerHp = getInt(props, prefix + "player.hp", 100);
        playerAttack = getInt(props, prefix + "player.attack", 15);
        playerDamageVariance = getInt(props, prefix + "player.damageVariance", 5);
        playerMaxCharge = getInt(props, prefix + "player.maxCharge", 100);
        playerChargeRate = getInt(props, prefix + "player.chargeRate", 2);
        enemyHp = getInt(props, prefix + "enemy.hp", 20);
        enemyAttack = getInt(props, prefix + "enemy.attack", 10);
        enemyDamageVariance = getInt(props, prefix + "enemy.damageVariance", 3);
        enemyMoveInterval = getInt(props, prefix + "enemy.moveInterval", 5);
        enemySightRange = getInt(props, prefix + "enemy.sightRange", 7);
        enemyBaseCount = getInt(props, prefix + "enemy.baseCount", 3);
    }

    /** 加载配置文件，不存在则自动生成 */
    private static Properties load(Difficulty difficulty) {
        File file = new File(CONFIG_PATH);
        if (!file.exists()) {
            generateDefaultConfigFile();
        }
        Properties props = new Properties();
        try (FileInputStream fis = new FileInputStream(file)) {
            props.load(fis);
        } catch (IOException e) {
            Logger.error("Failed to load config file: %s, using defaults.", e.getMessage());
        }
        return props;
    }

    /** 从 Properties 读取 int，失败则返回默认值 */
    private static int getInt(Properties props, String key, int defaultValue) {
        String value = props.getProperty(key);
        if (value == null) {
            return defaultValue;
        }
        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException e) {
            Logger.error("Invalid config value for '%s': %s, using default %d",
                    key, value, defaultValue);
            return defaultValue;
        }
    }

    /** 生成包含三难度默认配置的 properties 文件 */
    public static void generateDefaultConfigFile() {
        File file = new File(CONFIG_PATH);
        File parentDir = file.getParentFile();
        if (parentDir != null && !parentDir.exists()) {
            parentDir.mkdirs();
        }
        try (FileOutputStream fos = new FileOutputStream(file);
             OutputStreamWriter writer = new OutputStreamWriter(fos, StandardCharsets.UTF_8)) {
            writer.write("# Generated by GameConfig - edit to customize difficulty balance\n");
            writer.write("\n");
            writer.write("# ========== Easy ==========\n");
            writer.write("easy.player.hp=150\n");
            writer.write("easy.player.attack=12\n");
            writer.write("easy.player.damageVariance=3\n");
            writer.write("easy.player.maxCharge=80\n");
            writer.write("easy.player.chargeRate=3\n");
            writer.write("easy.enemy.hp=15\n");
            writer.write("easy.enemy.attack=5\n");
            writer.write("easy.enemy.damageVariance=2\n");
            writer.write("easy.enemy.moveInterval=10\n");
            writer.write("easy.enemy.sightRange=5\n");
            writer.write("easy.enemy.baseCount=2\n");
            writer.write("\n");
            writer.write("# ========== Balanced ==========\n");
            writer.write("balanced.player.hp=100\n");
            writer.write("balanced.player.attack=15\n");
            writer.write("balanced.player.damageVariance=5\n");
            writer.write("balanced.player.maxCharge=100\n");
            writer.write("balanced.player.chargeRate=2\n");
            writer.write("balanced.enemy.hp=20\n");
            writer.write("balanced.enemy.attack=10\n");
            writer.write("balanced.enemy.damageVariance=3\n");
            writer.write("balanced.enemy.moveInterval=5\n");
            writer.write("balanced.enemy.sightRange=7\n");
            writer.write("balanced.enemy.baseCount=3\n");
            writer.write("\n");
            writer.write("# ========== Hardcore ==========\n");
            writer.write("hardcore.player.hp=50\n");
            writer.write("hardcore.player.attack=10\n");
            writer.write("hardcore.player.damageVariance=8\n");
            writer.write("hardcore.player.maxCharge=150\n");
            writer.write("hardcore.player.chargeRate=1\n");
            writer.write("hardcore.enemy.hp=30\n");
            writer.write("hardcore.enemy.attack=15\n");
            writer.write("hardcore.enemy.damageVariance=5\n");
            writer.write("hardcore.enemy.moveInterval=3\n");
            writer.write("hardcore.enemy.sightRange=9\n");
            writer.write("hardcore.enemy.baseCount=4\n");
            writer.flush();
            Logger.info("Default config file generated: %s", CONFIG_PATH);
        } catch (IOException e) {
            Logger.error("Failed to generate config file: %s", e.getMessage());
        }
    }
}
